import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../services/diamond_wallet_service.dart';
import 'recharge_checkout_screen.dart';

class RechargeScreen extends StatefulWidget {
  final int initialTab;
  const RechargeScreen({super.key, this.initialTab = 0});
  @override State<RechargeScreen> createState() => _RechargeScreenState();
}

class _RechargeScreenState extends State<RechargeScreen> {
  late int tab;
  int selected = 1;
  bool _checkedPassword = false;
  static const packages = [
    (amount:500,price:4.99,diamonds:50,image:'assets/images/coins/coins_500.png'),
    (amount:1200,price:9.99,diamonds:120,image:'assets/images/coins/coins_1200.png'),
    (amount:2500,price:19.99,diamonds:250,image:'assets/images/coins/coins_2500.png'),
    (amount:5000,price:34.99,diamonds:500,image:'assets/images/coins/coins_5000.png'),
    (amount:12000,price:66.99,diamonds:1200,image:'assets/images/coins/coins_12000.png'),
    (amount:25000,price:99.99,diamonds:2500,image:'assets/images/coins/coins_25000.png'),
  ];

  @override void initState(){super.initState();tab=widget.initialTab==1?1:0;WidgetsBinding.instance.addPostFrameCallback((_){if(tab==1)_ensurePassword();});}
  void _msg(String t)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));

  Future<void> _ensurePassword() async {
    if(_checkedPassword)return;
    _checkedPassword=true;
    try{
      final snap=await DiamondWalletService.watchWallet().first;
      if(!mounted||snap.data()?['diamondPasswordSet']==true)return;
      await _createPasswordDialog();
    }catch(e){if(mounted)_msg('تعذر قراءة إعدادات محفظة الألماس: $e');}
  }

  Future<void> _createPasswordDialog() async {
    final p=TextEditingController(),c=TextEditingController();
    await showDialog<void>(context:context,barrierDismissible:false,builder:(d)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(backgroundColor:const Color(0xFF101222),title:const Text('إنشاء كلمة سر الألماس',style:TextStyle(color:Colors.white)),content:Column(mainAxisSize:MainAxisSize.min,children:[const Text('هذه المرة الأولى. أنشئ كلمة سر للمعاملات والتحويلات.',style:TextStyle(color:Colors.white70)),const SizedBox(height:12),_dialogField(p,'كلمة السر'),const SizedBox(height:10),_dialogField(c,'تأكيد كلمة السر')]),actions:[FilledButton(onPressed:()async{if(p.text.length<6){_msg('كلمة السر 6 خانات على الأقل.');return;}if(p.text!=c.text){_msg('كلمتا السر غير متطابقتين.');return;}try{await DiamondWalletService.setInitialPassword(p.text);if(d.mounted)Navigator.pop(d);}catch(e){_msg('$e');}},child:const Text('حفظ'))])));
  }

  @override Widget build(BuildContext context){final diamond=tab==1;return Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:const Color(0xFF05060D),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,28),children:[
    Row(children:[IconButton(onPressed:()=>Navigator.maybePop(context),icon:const Icon(Icons.arrow_forward_ios_rounded,color:Colors.white)),Expanded(child:Text(diamond?'محفظة الألماس':'شحن الرصيد',textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900))),const SizedBox(width:48)]),
    const SizedBox(height:10),Container(height:58,decoration:BoxDecoration(color:const Color(0xFF101222),borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0xFF7B35FF))),child:Row(children:[_tab('🪙 العملات الذهبية',0),_tab('💎 الألماس',1)])),
    const SizedBox(height:18),_asset('assets/images/recharge_banner.png',145),
    if(diamond)...[const SizedBox(height:12),StreamBuilder<DocumentSnapshot<Map<String,dynamic>>>(stream:DiamondWalletService.watchWallet(),builder:(_,s){final n=(s.data?.data()?['diamonds'] as num?)?.toInt()??0;return Container(padding:const EdgeInsets.symmetric(horizontal:18,vertical:13),decoration:BoxDecoration(color:const Color(0xFF101222),borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0xFF5635A7))),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('رصيد الألماس الحالي',style:TextStyle(color:Color(0xFFC9B8FF),fontWeight:FontWeight.w800)),Text('💎 ${_format(n)}',style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900))]));})],
    const SizedBox(height:20),Text(diamond?'🪙 اختر باقة العملات المناسبة لك':'🪙 اختر الباقة المناسبة لك',style:const TextStyle(color:Color(0xFFC9B8FF),fontSize:18,fontWeight:FontWeight.w900)),if(diamond)const Padding(padding:EdgeInsets.only(top:5),child:Text('الألماس يأتي من المهام والهدايا المستلمة، ويمكن استبداله بالعملات.',style:TextStyle(color:Colors.white54,fontSize:13))),const SizedBox(height:12),
    GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:packages.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:10,mainAxisSpacing:12,childAspectRatio:.72),itemBuilder:(_,i){final p=packages[i],active=selected==i;return InkWell(onTap:()=>setState(()=>selected=i),borderRadius:BorderRadius.circular(17),child:Container(decoration:BoxDecoration(color:const Color(0xFF101222),borderRadius:BorderRadius.circular(17),border:Border.all(color:active?const Color(0xFFBD43FF):Colors.white10,width:active?1.5:1)),child:Column(children:[if(i==1)_tag('🔥 الأكثر شعبية',const Color(0xFFFF3B72)),if(i==5)_tag('👑 أفضل قيمة',const Color(0xFF8A2CFF)),Expanded(child:Center(child:SizedBox(width:64,height:64,child:Padding(padding:const EdgeInsets.all(7),child:Image.asset(p.image,fit:BoxFit.contain,errorBuilder:(_,__,___)=>const Icon(Icons.monetization_on_rounded,color:Color(0xFFFFC93D),size:42))))),Text('🪙 ${_format(p.amount)}',style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:8),Container(width:double.infinity,padding:const EdgeInsets.symmetric(vertical:10),decoration:const BoxDecoration(color:Color(0xFF201071),borderRadius:BorderRadius.vertical(bottom:Radius.circular(16))),child:Text(diamond?'💎 ${_format(p.diamonds)}':'\$ ${p.price.toStringAsFixed(2)}',textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)))])));}),
    const SizedBox(height:20),const Divider(color:Colors.white12),const SizedBox(height:12),if(diamond)SizedBox(height:54,child:FilledButton.icon(onPressed:_openGiftSheet,icon:const Icon(Icons.card_giftcard_rounded),label:const Text('إهداء العملات لصديق 🎁',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),style:FilledButton.styleFrom(backgroundColor:const Color(0xFF7130D9),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)))))else...[const Text('🎁 لديك كود ترويجي؟',style:TextStyle(color:Color(0xFFC9B8FF),fontWeight:FontWeight.w800)),const SizedBox(height:10),TextField(style:const TextStyle(color:Colors.white),decoration:InputDecoration(hintText:'أدخل الكود هنا',hintStyle:const TextStyle(color:Colors.white38),filled:true,fillColor:const Color(0xFF101222),border:OutlineInputBorder(borderRadius:BorderRadius.circular(15))))],
    const SizedBox(height:16),_asset('assets/images/recharge_features.png',105),const SizedBox(height:16),SizedBox(height:54,child:FilledButton(onPressed:()async{final p=packages[selected];if(diamond){try{await DiamondWalletService.exchangeDiamondsForCoins(diamondCost:p.diamonds,coins:p.amount);if(mounted)_msg('تم استبدال الألماس بـ ${_format(p.amount)} عملة.');}catch(e){_msg('$e');}return;}Navigator.push(context,MaterialPageRoute(builder:(_)=>const RechargeCheckoutScreen(),settings:RouteSettings(arguments:{'coins':p.amount,'price':p.price,'currencyType':'coins'})));},style:FilledButton.styleFrom(backgroundColor:const Color(0xFF8A32FF),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))),child:Text(diamond?'استبدال الألماس بالعملات':'متابعة إلى الدفع',style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900))))
  ])))));}

  Future<void> _openGiftSheet() async {final id=TextEditingController(),amount=TextEditingController();Map<String,dynamic>? recipient;await showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:const Color(0xFF101222),shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(24))),builder:(ctx)=>StatefulBuilder(builder:(ctx,setLocal)=>Directionality(textDirection:TextDirection.rtl,child:Padding(padding:EdgeInsets.fromLTRB(20,22,20,MediaQuery.of(ctx).viewInsets.bottom+24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('إهداء العملات لصديق 🎁',style:TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:14),_input(id,'ID المستلم',Icons.badge_outlined),const SizedBox(height:8),OutlinedButton(onPressed:()async{try{final r=await DiamondWalletService.findUserByPublicId(id.text);setLocal(()=>recipient=r);if(r==null)_msg('لم يتم العثور على مستخدم بهذا الـ ID.');}catch(e){_msg('$e');}},child:const Text('تم / تحقق من المستخدم')),if(recipient!=null)...[const SizedBox(height:12),_recipientCard(recipient!)],const SizedBox(height:12),_input(amount,'عدد العملات — الحد الأدنى 100',Icons.monetization_on_outlined),const SizedBox(height:16),FilledButton(onPressed:recipient==null?null:()async{final n=int.tryParse(amount.text)??0;if(n<100){_msg('الحد الأدنى 100 عملة.');return;}Navigator.pop(ctx);await _requestTransferPassword(recipient!['uid'].toString(),n);},style:FilledButton.styleFrom(backgroundColor:const Color(0xFF8A32FF),minimumSize:const Size.fromHeight(52)),child:const Text('إرسال',style:TextStyle(fontWeight:FontWeight.w900)))])))));}

  Future<void> _requestTransferPassword(String recipientUid,int amount) async {final p=TextEditingController();await showDialog<void>(context:context,builder:(d)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(backgroundColor:const Color(0xFF101222),title:const Text('كلمة سر الألماس',style:TextStyle(color:Colors.white)),content:_dialogField(p,'كلمة السر'),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('إلغاء')),FilledButton(onPressed:()async{try{await DiamondWalletService.transferCoins(recipientUid:recipientUid,amount:amount,password:p.text);if(d.mounted)Navigator.pop(d);if(mounted)_msg('تم إرسال $amount عملة بنجاح.');}catch(e){_msg('$e');}},child:const Text('تأكيد الإرسال'))])));}
  Widget _recipientCard(Map<String,dynamic>u){final name=(u['displayName']??u['username']??'مستخدم').toString(),id=(u['publicId']??'').toString(),url=(u['profileImageUrl']??u['avatarUrl']??'').toString();return Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xFF080A14),borderRadius:BorderRadius.circular(14)),child:Row(children:[CircleAvatar(radius:24,backgroundImage:url.isNotEmpty?NetworkImage(url):null,child:url.isEmpty?const Icon(Icons.person):null),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),Text('ID: $id',style:const TextStyle(color:Colors.white54))]))]));}
  Widget _dialogField(TextEditingController c,String hint)=>TextField(controller:c,obscureText:true,style:const TextStyle(color:Colors.white),decoration:InputDecoration(hintText:hint,hintStyle:const TextStyle(color:Colors.white38),filled:true,fillColor:const Color(0xFF080A14),border:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:BorderSide.none)));
  Widget _input(TextEditingController c,String hint,IconData icon)=>TextField(controller:c,keyboardType:TextInputType.number,style:const TextStyle(color:Colors.white),decoration:InputDecoration(prefixIcon:Icon(icon,color:const Color(0xFFC9B8FF)),hintText:hint,hintStyle:const TextStyle(color:Colors.white38),filled:true,fillColor:const Color(0xFF080A14),border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none)));
  Widget _tab(String text,int index){final active=tab==index;return Expanded(child:InkWell(onTap:(){setState((){tab=index;selected=1;});if(index==1)_ensurePassword();},borderRadius:BorderRadius.circular(15),child:Container(alignment:Alignment.center,decoration:active?BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF9A2EFF),Color(0xFF291065)]),borderRadius:BorderRadius.circular(15)):null,child:Text(text,style:TextStyle(color:active?Colors.white:const Color(0xFFB9A7E8),fontWeight:active?FontWeight.w800:FontWeight.w700)))));}
  Widget _tag(String t,Color c)=>Container(width:double.infinity,padding:const EdgeInsets.symmetric(vertical:4),decoration:BoxDecoration(color:c,borderRadius:const BorderRadius.vertical(top:Radius.circular(16))),child:Text(t,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:10,fontWeight:FontWeight.w800)));
  Widget _asset(String path,double h)=>ClipRRect(borderRadius:BorderRadius.circular(18),child:Image.asset(path,height:h,width:double.infinity,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(height:h,color:const Color(0xFF121426))));
  String _format(int n)=>n.toString().replaceAllMapped(RegExp(r'(?<=\d)(?=(\d{3})+(?!\d))'),(_)=>',');
}
