import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter/services.dart';
import '../bloc/user_bloc.dart';
import '../../auth/bloc/auth_bloc.dart';
import '../../wallet/screens/recharge_screen.dart';
import '../../../shared/widgets/custom_button.dart';
import '../../../shared/widgets/loading_indicator.dart';
import '../../../services/navigation_service.dart';

class ProfileScreen extends StatefulWidget{const ProfileScreen({super.key});@override State<ProfileScreen> createState()=>_ProfileScreenState();}
class _ProfileScreenState extends State<ProfileScreen> with SingleTickerProviderStateMixin{
 late final TabController _tabs;@override void initState(){super.initState();_tabs=TabController(length:3,vsync:this);_load();}@override void dispose(){_tabs.dispose();super.dispose();}
 void _load(){final a=context.read<AuthBloc>().state;final id=a is Authenticated?a.user.uid:null;if(id!=null)context.read<UserBloc>().add(LoadUserProfile(id));}
 Future<void> _edit()async{final changed=await Navigator.of(context).pushNamed(AppRoutes.editProfile);if(changed==true&&mounted)_load();}
 void _recharge(int tab)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>RechargeScreen(initialTab:tab)));
 Future<void> _logout()async{final yes=await showDialog<bool>(context:context,builder:(d)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(backgroundColor:const Color(0xFF101827),title:const Text('تسجيل الخروج',style:TextStyle(color:Colors.white)),content:const Text('هل أنت متأكد أنك تريد تسجيل الخروج من حسابك؟',style:TextStyle(color:Colors.white70)),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.redAccent),onPressed:()=>Navigator.pop(d,true),child:const Text('تسجيل الخروج'))])));if(yes==true&&mounted){context.read<AuthBloc>().add(SignOutRequested());NavigationService.navigateToAndRemoveUntil(AppRoutes.authChoice);}}
 String _text(Map<String,dynamic>p,String k,[String f='—']){final v=p[k];return v==null||v.toString().trim().isEmpty?f:v.toString();}int _num(Map<String,dynamic>p,List<String>ks){for(final k in ks){final v=p[k];if(v is num)return v.toInt();final n=int.tryParse(v?.toString()??'');if(n!=null)return n;}return 0;}
 ImageProvider? _avatar(Map<String,dynamic>p){final u=p['profileImageUrl']??p['avatarUrl'];if(u is String&&u.isNotEmpty)return NetworkImage(u);final a=p['profileAvatarAsset'];if(a is String&&a.isNotEmpty)return AssetImage(a);return null;}
 List<String> _ids(Map<String,dynamic>p){final r=<String>[];final c=p['publicId']?.toString();if(c!=null&&c.isNotEmpty)r.add(c);final h=p['publicIdHistory'];if(h is List)for(final x in h){final id=x is Map?x['id']?.toString():x.toString();if(id!=null&&id.isNotEmpty&&!r.contains(id))r.add(id);}return r;}
 Future<void> _copyId(Map<String,dynamic>p)async{final ids=_ids(p);if(ids.isEmpty)return;String? id;if(ids.length==1)id=ids.first;else{id=await showModalBottomSheet<String>(context:context,backgroundColor:const Color(0xFF101827),builder:(c)=>Directionality(textDirection:TextDirection.rtl,child:SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[const Padding(padding:EdgeInsets.all(16),child:Text('اختر ID للنسخ',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.bold))),...ids.asMap().entries.map((e)=>ListTile(title:Text(e.value,style:const TextStyle(color:Colors.white)),subtitle:Text(e.key==0?'ID الحالي':'ID سابق',style:const TextStyle(color:Colors.white54)),trailing:const Icon(Icons.copy,color:Color(0xFF8B5CF6)),onTap:()=>Navigator.pop(c,e.value)))]))));}if(id!=null){await Clipboard.setData(ClipboardData(text:id));if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم نسخ ID')));}}
 @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:const Color(0xFF020711),body:BlocBuilder<UserBloc,UserState>(builder:(context,state){if(state is UserLoading)return const LoadingIndicator();if(state is UserError)return Center(child:CustomButton(text:'إعادة المحاولة',onPressed:_load));final p=state is UserProfileLoaded?state.profile:state is UserProfileUpdated?state.profile:null;if(p==null)return const Center(child:Text('لا توجد بيانات للملف الشخصي'));return NestedScrollView(headerSliverBuilder:(_,__)=>[SliverAppBar(backgroundColor:const Color(0xFF07111F),leading:IconButton(icon:const Icon(Icons.arrow_forward_ios_rounded),onPressed:()=>Navigator.maybePop(context)),expandedHeight:350,pinned:true,flexibleSpace:FlexibleSpaceBar(background:_header(p)),actions:[IconButton(tooltip:'تعديل الملف الشخصي',icon:const Icon(Icons.edit_rounded),onPressed:_edit),IconButton(tooltip:'الإعدادات',icon:const Icon(Icons.settings_rounded),onPressed:()=>Navigator.pushNamed(context,AppRoutes.settings))]),SliverPersistentHeader(pinned:true,delegate:_Delegate(TabBar(controller:_tabs,labelColor:const Color(0xFFFFD54A),unselectedLabelColor:Colors.white54,tabs:const[Tab(text:'حول'),Tab(text:'الغرف'),Tab(text:'الهدايا')])) )],body:TabBarView(controller:_tabs,children:[_about(p),const Center(child:Text('الغرف')),const Center(child:Text('الهدايا'))]));})));
 Widget _header(Map<String,dynamic>p){final img=_avatar(p),cover=_text(p,'coverImageUrl',''),name=_text(p,'displayName',_text(p,'username')),id=_text(p,'publicId');return Container(decoration:BoxDecoration(gradient:cover.isEmpty?const RadialGradient(center:Alignment(.6,-.5),radius:1.3,colors:[Color(0xFF251044),Color(0xFF07111F),Color(0xFF020711)]):null,image:cover.isNotEmpty?DecorationImage(image:NetworkImage(cover),fit:BoxFit.cover,colorFilter:ColorFilter.mode(Colors.black.withValues(alpha:.38),BlendMode.darken)):null),padding:const EdgeInsets.fromLTRB(20,85,20,18),child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[CircleAvatar(radius:52,backgroundColor:const Color(0xFF171D31),backgroundImage:img,child:img==null?const Icon(Icons.person,size:58,color:Colors.white54):null),const SizedBox(height:10),Text(name,style:const TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:7),InkWell(onTap:()=>_copyId(p),borderRadius:BorderRadius.circular(16),child:Padding(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),child:Row(mainAxisSize:MainAxisSize.min,children:[Text('ID: $id',textDirection:TextDirection.ltr,style:const TextStyle(color:Color(0xFFFFD54A),fontWeight:FontWeight.w800)),const SizedBox(width:6),const Icon(Icons.copy_rounded,size:16,color:Color(0xFFFFD54A))]))),const SizedBox(height:12),Row(mainAxisAlignment:MainAxisAlignment.center,children:[_chip(Icons.monetization_on,'${_num(p,['coins','balance'])} عملة',0),const SizedBox(width:10),_chip(Icons.diamond,'${_num(p,['diamonds'])} ألماس',1)])]));}
 Widget _chip(IconData i,String t,int tab)=>InkWell(onTap:()=>_recharge(tab),borderRadius:BorderRadius.circular(20),child:Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),decoration:BoxDecoration(color:Colors.black.withValues(alpha:.38),borderRadius:BorderRadius.circular(20),border:Border.all(color:Colors.white24)),child:Row(children:[Icon(i,color:tab==0?const Color(0xFFFFD54A):const Color(0xFF66E1FF),size:18),const SizedBox(width:6),Text(t,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700)),const SizedBox(width:5),const Icon(Icons.add_circle_rounded,color:Color(0xFF9A5CFF),size:18)])));
 Widget _about(Map<String,dynamic>p)=>ListView(padding:const EdgeInsets.all(16),children:[_card('الملف الشخصي',[_row('ID',_text(p,'publicId')),_row('الاسم الظاهر',_text(p,'displayName')),_row('الموقع',_text(p,'location')),_row('نبذة',_text(p,'bio','لا توجد نبذة'))]),const SizedBox(height:16),_card('الرصيد',[_row('العملات',_num(p,['coins','balance']).toString()),_row('الألماس',_num(p,['diamonds']).toString())]),const SizedBox(height:24),CustomButton(text:'تسجيل الخروج',onPressed:_logout,isOutlined:true)]);
 Widget _card(String t,List<Widget>c)=>Card(color:const Color(0xFF0C1728),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(t,style:const TextStyle(color:Color(0xFFFFD54A),fontSize:17,fontWeight:FontWeight.w900)),const SizedBox(height:14),...c])));Widget _row(String l,String v)=>Padding(padding:const EdgeInsets.only(bottom:10),child:Row(children:[Text(l,style:const TextStyle(color:Colors.white54)),const Spacer(),Flexible(child:Text(v,textAlign:TextAlign.left,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700)))]));
}
class _Delegate extends SliverPersistentHeaderDelegate{final TabBar bar;_Delegate(this.bar);@override double get minExtent=>bar.preferredSize.height;@override double get maxExtent=>bar.preferredSize.height;@override Widget build(BuildContext c,double s,bool o)=>Container(color:const Color(0xFF07111F),child:bar);@override bool shouldRebuild(_Delegate old)=>false;}
