import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../features/auth/bloc/auth_bloc.dart';
import '../../features/wallet/screens/diamond_password_reset_screen.dart';
import '../../services/navigation_service.dart';

class SettingsScreen extends StatefulWidget { const SettingsScreen({super.key}); @override State<SettingsScreen> createState()=>_SettingsScreenState(); }
class _SettingsScreenState extends State<SettingsScreen> {
 static const _gold=Color(0xFFFFD166),_purple=Color(0xFF8B5CF6),_deep=Color(0xFF050814);bool _loggingOut=false;
 Future<void> _confirmLogout()async{if(_loggingOut)return;final confirmed=await showDialog<bool>(context:context,builder:(d)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(backgroundColor:const Color(0xFF101827),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18),side:const BorderSide(color:Color(0x558B5CF6))),title:const Row(children:[Icon(Icons.logout_rounded,color:Colors.redAccent),SizedBox(width:10),Text('تسجيل الخروج',style:TextStyle(color:Colors.white))]),content:const Text('هل أنت متأكد أنك تريد تسجيل الخروج من حسابك؟',style:TextStyle(color:Colors.white70,height:1.5)),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء',style:TextStyle(color:Colors.white70))),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.redAccent),onPressed:()=>Navigator.pop(d,true),child:const Text('تسجيل الخروج'))])));if(confirmed==true&&mounted){setState(()=>_loggingOut=true);context.read<AuthBloc>().add(SignOutRequested());}}
 void _soon(String f)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$f — سيتم تفعيلها لاحقاً')));void _diamond()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const DiamondPasswordResetScreen()));
 @override Widget build(BuildContext context)=>BlocListener<AuthBloc,AuthState>(listener:(context,state){if(state is Unauthenticated&&_loggingOut){NavigationService.navigateToAndRemoveUntil(AppRoutes.authChoice);}else if(state is AuthError&&_loggingOut){setState(()=>_loggingOut=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(state.message)));}},child:Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:_deep,body:Container(decoration:const BoxDecoration(gradient:RadialGradient(center:Alignment(.6,-.7),radius:1.25,colors:[Color(0xFF24103F),Color(0xFF07111E),_deep])),child:SafeArea(child:Column(children:[_header(),Expanded(child:SingleChildScrollView(padding:const EdgeInsets.fromLTRB(16,8,16,28),child:Column(children:[_profile(),const SizedBox(height:18),_menu([_SettingItem(Icons.person_rounded,'تعديل الملف الشخصي',()=>NavigationService.navigateTo(AppRoutes.editProfile)),_SettingItem(Icons.shield_rounded,'الحساب والأمان',()=>_soon('الحساب والأمان')),_SettingItem(Icons.diamond_rounded,'تغيير كلمة سر الألماس',_diamond,subtitle:'يتطلب التحقق برقم الهاتف وOTP'),_SettingItem(Icons.account_balance_wallet_rounded,'محفظتي',()=>_soon('المحفظة')),_SettingItem(Icons.palette_rounded,'مظهر التطبيق',()=>_soon('مظهر التطبيق')),_SettingItem(Icons.notifications_rounded,'الإشعارات',()=>_soon('الإشعارات')),_SettingItem(Icons.lock_rounded,'الخصوصية',()=>_soon('الخصوصية')),_SettingItem(Icons.language_rounded,'اللغة',()=>_soon('اللغات'),subtitle:'العربية'),_SettingItem(Icons.help_rounded,'المساعدة',()=>_soon('المساعدة')),_SettingItem(Icons.info_rounded,'حول التطبيق',()=>_soon('حول التطبيق'),subtitle:'Shadow Live')]),const SizedBox(height:18),_vip(),const SizedBox(height:18),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:_loggingOut?null:_confirmLogout,icon:_loggingOut?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.logout_rounded),label:Text(_loggingOut?'جارٍ تسجيل الخروج...':'تسجيل الخروج'),style:OutlinedButton.styleFrom(foregroundColor:Colors.redAccent,side:const BorderSide(color:Color(0x66FF5252)),padding:const EdgeInsets.symmetric(vertical:15),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)))))]))) ]))))));
 Widget _header()=>Padding(padding:const EdgeInsets.fromLTRB(12,8,12,12),child:Row(children:[IconButton(onPressed:_loggingOut?null:()=>Navigator.maybePop(context),icon:const Icon(Icons.arrow_forward_ios_rounded,color:Colors.white)),const Expanded(child:Column(children:[Icon(Icons.mic_rounded,color:_gold,size:30),SizedBox(height:2),Text('SHADOW LIVE',style:TextStyle(color:_gold,fontWeight:FontWeight.w900,letterSpacing:1.2,fontSize:14))])),const SizedBox(width:48)]));
 Widget _profile()=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xCC0B1322),borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0x444D67FF))),child:const Row(children:[CircleAvatar(radius:36,backgroundColor:Color(0xFF25124D),child:Icon(Icons.person_rounded,color:_gold,size:42)),SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('حسابي',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:20)),SizedBox(height:6),Text('إدارة معلومات الحساب والإعدادات',style:TextStyle(color:Colors.white54,fontSize:13))])),Icon(Icons.workspace_premium_rounded,color:_gold,size:30)]));
 Widget _menu(List<_SettingItem> items)=>Container(decoration:BoxDecoration(color:const Color(0xCC0B1322),borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0x334D67FF))),child:Column(children:List.generate(items.length,(i){final x=items[i];return Column(children:[ListTile(enabled:!_loggingOut,minVerticalPadding:12,leading:Container(width:42,height:42,decoration:BoxDecoration(borderRadius:BorderRadius.circular(12),gradient:const LinearGradient(colors:[Color(0xFF25124D),Color(0xFF111827)])),child:Icon(x.icon,color:_purple,size:24)),title:Text(x.title,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w700)),subtitle:x.subtitle==null?null:Text(x.subtitle!,style:const TextStyle(color:Colors.white54,fontSize:12)),trailing:const Icon(Icons.chevron_left_rounded,color:Colors.white38),onTap:x.onTap),if(i!=items.length-1)const Divider(height:1,indent:70,color:Color(0x221fffffff))]);})));
 Widget _vip()=>Container(width:double.infinity,padding:const EdgeInsets.all(18),decoration:BoxDecoration(borderRadius:BorderRadius.circular(22),gradient:const LinearGradient(begin:Alignment.topRight,end:Alignment.bottomLeft,colors:[Color(0xFF2A153F),Color(0xFF120C20),Color(0xFF1D1207)]),border:Border.all(color:const Color(0x88FFD166))),child:const Column(children:[Icon(Icons.workspace_premium_rounded,size:56,color:_gold),SizedBox(height:8),Text('كن مميزاً',style:TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Shadow Live VIP',style:TextStyle(color:Colors.white70,fontSize:16)),SizedBox(height:12),Text('مزايا VIP ستتوفر في مرحلة نظام العضويات',textAlign:TextAlign.center,style:TextStyle(color:Colors.white54))]));
}
class _SettingItem{final IconData icon;final String title;final VoidCallback? onTap;final String? subtitle;const _SettingItem(this.icon,this.title,this.onTap,{this.subtitle});}
