import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../wallet/screens/recharge_screen.dart';

class HomeScreen extends StatefulWidget{const HomeScreen({super.key});@override State<HomeScreen> createState()=>_HomeScreenState();}
class _HomeScreenState extends State<HomeScreen>{
 Map<String,dynamic>? _userData;static const _bg=Color(0xFF05060D),_card=Color(0xFF111321),_gold=Color(0xFFFFD54A),_purple=Color(0xFF8A3DFF);
 @override void initState(){super.initState();_loadUser();}
 Future<void> _loadUser()async{final u=FirebaseAuth.instance.currentUser;if(u==null)return;try{final s=await FirebaseFirestore.instance.collection('users').doc(u.uid).get();if(mounted)setState(()=>_userData=s.data());}catch(_){}}
 void _recharge(int tab)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>RechargeScreen(initialTab:tab)));
 @override Widget build(BuildContext context){final name=(_userData?['displayName']??_userData?['username']??'صديقنا').toString(),level=(_userData?['level']??1).toString(),coins=(_userData?['coins']??0).toString(),diamonds=(_userData?['diamonds']??0).toString();return Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:_bg,body:Container(decoration:const BoxDecoration(gradient:RadialGradient(center:Alignment(.7,-.9),radius:1.25,colors:[Color(0xFF251047),_bg])),child:SafeArea(bottom:false,child:RefreshIndicator(onRefresh:_loadUser,child:ListView(padding:const EdgeInsets.fromLTRB(16,12,16,28),children:[_header(name,level,coins,diamonds),const SizedBox(height:18),_search(),const SizedBox(height:18),_hero(),const SizedBox(height:24),_title('غرف مقترحة'),const SizedBox(height:12),SizedBox(height:170,child:ListView(scrollDirection:Axis.horizontal,children:const[_RoomCard('سوالف المساء','128',Icons.nightlife),_RoomCard('أصدقاء جدد','94',Icons.groups_rounded),_RoomCard('موسيقى ووناسة','76',Icons.music_note_rounded)])),const SizedBox(height:24),_title('استكشف Shadow Live'),const SizedBox(height:12),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),mainAxisSpacing:12,crossAxisSpacing:12,childAspectRatio:1.65,children:const[_Feature('الأصدقاء','اكتشف أشخاصاً جدد',Icons.people_alt_rounded),_Feature('الألعاب','العب واربح',Icons.sports_esports_rounded),_Feature('الفعاليات','لا تفوّت الجديد',Icons.celebration_rounded),_Feature('الترتيب','نجوم المجتمع',Icons.emoji_events_rounded)])])))))));}
 Widget _header(String name,String level,String coins,String diamonds)=>Row(children:[Container(width:48,height:48,decoration:BoxDecoration(shape:BoxShape.circle,gradient:const LinearGradient(colors:[_gold,_purple]),border:Border.all(color:Colors.white24)),child:const Icon(Icons.person_rounded,color:Colors.white,size:28)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('أهلاً، $name',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w800)),Text('LV.$level',style:const TextStyle(color:_gold,fontSize:11,fontWeight:FontWeight.w800))])),_wallet(Icons.monetization_on_rounded,coins,_gold,0),const SizedBox(width:6),_wallet(Icons.diamond_rounded,diamonds,const Color(0xFF64D8FF),1),const SizedBox(width:6),const Icon(Icons.notifications_none_rounded,color:Colors.white)]);
 Widget _wallet(IconData icon,String value,Color color,int tab)=>InkWell(onTap:()=>_recharge(tab),borderRadius:BorderRadius.circular(14),child:Container(padding:const EdgeInsets.symmetric(horizontal:6,vertical:7),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.06),borderRadius:BorderRadius.circular(14),border:Border.all(color:Colors.white10)),child:Row(children:[Icon(icon,color:color,size:15),const SizedBox(width:3),Text(value,style:const TextStyle(color:Colors.white,fontSize:11,fontWeight:FontWeight.w700)),const SizedBox(width:3),const Icon(Icons.add_circle_rounded,color:Color(0xFF9A5CFF),size:15)])));
 Widget _search()=>Container(height:48,padding:const EdgeInsets.symmetric(horizontal:14),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(16),border:Border.all(color:Colors.white10)),child:const Row(children:[Icon(Icons.search_rounded,color:Colors.white54),SizedBox(width:10),Text('ابحث عن غرف، أصدقاء، ألعاب...',style:TextStyle(color:Colors.white54,fontSize:13))]));
 Widget _hero()=>Container(height:175,padding:const EdgeInsets.all(20),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(colors:[Color(0xFF5A19B8),Color(0xFF17103B),Color(0xFF08101E)]),border:Border.all(color:_purple)),child:const Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text('صوتك يجمعنا',style:TextStyle(color:_gold,fontSize:25,fontWeight:FontWeight.w900)),SizedBox(height:8),Text('ادخل الغرف، تعرّف على أصدقاء\nوعِش اللحظة مع مجتمعك',style:TextStyle(color:Colors.white70,height:1.5,fontSize:13))])),Icon(Icons.mic_rounded,color:_gold,size:70)]));
 Widget _title(String t)=>Text(t,style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900));
}
class _RoomCard extends StatelessWidget{final String t,p;final IconData i;const _RoomCard(this.t,this.p,this.i);@override Widget build(BuildContext c)=>Container(width:145,margin:const EdgeInsetsDirectional.only(end:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(borderRadius:BorderRadius.circular(20),gradient:const LinearGradient(colors:[Color(0xFF251A42),Color(0xFF10121D)]),border:Border.all(color:Colors.white10)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(radius:27,backgroundColor:const Color(0xFF372064),child:Icon(i,color:const Color(0xFFFFD54A))),const Spacer(),Text(t,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),Text('$p متصل',style:const TextStyle(color:Colors.white54,fontSize:11))]));}
class _Feature extends StatelessWidget{final String t,s;final IconData i;const _Feature(this.t,this.s,this.i);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xFF111321),borderRadius:BorderRadius.circular(18),border:Border.all(color:Colors.white10)),child:Row(children:[Icon(i,color:const Color(0xFF8A3DFF),size:28),const SizedBox(width:10),Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),Text(s,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white38,fontSize:10))]))]));}
