import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../bloc/auth_bloc.dart';
import '../setup_route.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});
  @override State<LoginScreen> createState()=>_LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen>{
  final _phoneController=TextEditingController();
  final _otpControllers=List.generate(6,(_)=>TextEditingController());
  final _otpFocus=List.generate(6,(_)=>FocusNode());
  String _countryCode='+971'; String? _verificationId; bool _otpPage=false,_isVerifyingOtp=false; Timer? _timer; int _seconds=120;
  static const _gold=Color(0xFFFFD54A),_pink=Color(0xFFE000FF),_green=Color(0xFF25D366);
  static const _countries=<MapEntry<String,String>>[
    MapEntry('+971','🇦🇪 الإمارات'),MapEntry('+966','🇸🇦 السعودية'),MapEntry('+973','🇧🇭 البحرين'),MapEntry('+965','🇰🇼 الكويت'),MapEntry('+968','🇴🇲 عُمان'),MapEntry('+974','🇶🇦 قطر'),MapEntry('+962','🇯🇴 الأردن'),MapEntry('+963','🇸🇾 سوريا'),MapEntry('+961','🇱🇧 لبنان'),MapEntry('+970','🇵🇸 فلسطين'),MapEntry('+964','🇮🇶 العراق'),MapEntry('+20','🇪🇬 مصر'),MapEntry('+249','🇸🇩 السودان'),MapEntry('+218','🇱🇾 ليبيا'),MapEntry('+216','🇹🇳 تونس'),MapEntry('+213','🇩🇿 الجزائر'),MapEntry('+212','🇲🇦 المغرب'),MapEntry('+222','🇲🇷 موريتانيا'),MapEntry('+252','🇸🇴 الصومال'),MapEntry('+253','🇩🇯 جيبوتي'),MapEntry('+269','🇰🇲 جزر القمر'),MapEntry('+967','🇾🇪 اليمن'),MapEntry('+90','🇹🇷 تركيا'),MapEntry('+1','🇺🇸 الولايات المتحدة'),MapEntry('+44','🇬🇧 المملكة المتحدة'),MapEntry('+33','🇫🇷 فرنسا'),MapEntry('+49','🇩🇪 ألمانيا'),MapEntry('+39','🇮🇹 إيطاليا'),MapEntry('+34','🇪🇸 إسبانيا'),MapEntry('+31','🇳🇱 هولندا'),MapEntry('+32','🇧🇪 بلجيكا'),MapEntry('+41','🇨🇭 سويسرا'),MapEntry('+43','🇦🇹 النمسا'),MapEntry('+46','🇸🇪 السويد'),MapEntry('+47','🇳🇴 النرويج'),MapEntry('+45','🇩🇰 الدنمارك'),MapEntry('+358','🇫🇮 فنلندا'),MapEntry('+353','🇮🇪 أيرلندا'),MapEntry('+351','🇵🇹 البرتغال'),MapEntry('+30','🇬🇷 اليونان'),MapEntry('+48','🇵🇱 بولندا')];
  @override void dispose(){_timer?.cancel();_phoneController.dispose();for(final c in _otpControllers)c.dispose();for(final f in _otpFocus)f.dispose();super.dispose();}
  String _digits(String v){const a='٠١٢٣٤٥٦٧٨٩',p='۰۱۲۳۴۵۶۷۸۹',e='0123456789';final b=StringBuffer();for(final x in v.split('')){final ai=a.indexOf(x),pi=p.indexOf(x);if(ai>=0)b.write(e[ai]);else if(pi>=0)b.write(e[pi]);else if(RegExp(r'[0-9]').hasMatch(x))b.write(x);}return b.toString();}
  String get _fullPhone=>'$_countryCode${_digits(_phoneController.text).replaceFirst(RegExp(r'^0+'),'')}';
  String get _otp=>_otpControllers.map((e)=>e.text).join();
  void _message(String text)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text)));
  bool _validPhone(){if(_digits(_phoneController.text).length<7){_message('أدخل رقم هاتف صحيح');return false;}return true;}
  void _sendSms(){if(!_validPhone())return;context.read<AuthBloc>().add(PhoneAuthRequested(_fullPhone));}
  void _sendWhatsApp(){if(!_validPhone())return;_message('زر WhatsApp جاهز. سيتم تفعيل إرسال الرمز عند ربط مزود WhatsApp OTP بالخادم.');}
  void _startTimer(){_timer?.cancel();_seconds=120;_timer=Timer.periodic(const Duration(seconds:1),(t){if(!mounted){t.cancel();return;}setState(()=>_seconds--);if(_seconds<=0)t.cancel();});}
  void _handleOtp(int i,String raw){final v=_digits(raw);if(v.length>1){final d=v.substring(0,v.length.clamp(0,6));for(var x=0;x<6;x++)_otpControllers[x].text=x<d.length?d[x]:'';_otpFocus[d.length>=6?5:d.length].requestFocus();setState((){});if(d.length==6)_verify();return;}if(v.isEmpty){_otpControllers[i].clear();if(i>0)_otpFocus[i-1].requestFocus();setState((){});return;}_otpControllers[i].text=v;if(i<5)_otpFocus[i+1].requestFocus();setState((){});if(_otp.length==6)_verify();}
  void _verify(){if(_isVerifyingOtp)return;if(_verificationId==null){_message('لم يتم إرسال رمز التحقق بعد');return;}if(_otp.length!=6){_message('أدخل رمز التحقق المكوّن من 6 أرقام');return;}setState(()=>_isVerifyingOtp=true);context.read<AuthBloc>().add(PhoneCodeSubmitted(_verificationId!,_otp));}
  void _route(Authenticated s){final d=setupDestination(s.userData);if(d=='/profile-setup'){setState(()=>_otpPage=false);Navigator.of(context).pushNamed(d);}else{Navigator.of(context).pushNamedAndRemoveUntil(d,(_)=>false);}}

  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:const Color(0xFF03050D),body:BlocConsumer<AuthBloc,AuthState>(listener:(context,state){if(state is AuthError){if(_isVerifyingOtp)setState(()=>_isVerifyingOtp=false);_message(state.message);}if(state is PhoneCodeSent){setState((){_verificationId=state.verificationId;_otpPage=true;_isVerifyingOtp=false;});_startTimer();Future.delayed(const Duration(milliseconds:250),(){if(mounted)_otpFocus.first.requestFocus();});}if(state is Authenticated)_route(state);},builder:(context,state)=>Container(decoration:const BoxDecoration(gradient:RadialGradient(center:Alignment(.8,-.6),radius:1.25,colors:[Color(0xFF291050),Color(0xFF07111D),Color(0xFF03050D)])),child:SafeArea(child:Column(children:[_header(),Expanded(child:AnimatedSwitcher(duration:const Duration(milliseconds:250),child:_otpPage?_otpView(state):_phoneView(state)))]))))));

  Widget _header()=>Stack(children:[SizedBox(width:double.infinity,height:210,child:Image.asset('assets/images/phone_header.png',fit:BoxFit.cover)),Positioned(top:12,right:12,child:Container(width:46,height:46,decoration:BoxDecoration(shape:BoxShape.circle,color:const Color(0x66101522),border:Border.all(color:Colors.white54)),child:IconButton(icon:const Icon(Icons.arrow_back_ios_new_rounded,color:Colors.white),onPressed:(){if(_otpPage){setState(()=>_otpPage=false);}else{Navigator.maybePop(context);}})))]);
  BoxDecoration _field()=>BoxDecoration(color:const Color(0x99111A2B),borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0xFF34435A)));

  Widget _phoneView(AuthState state)=>SingleChildScrollView(key:const ValueKey('phone'),padding:const EdgeInsets.fromLTRB(20,20,20,30),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const SizedBox(height:10),const Text('رقم الهاتف',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:10),const Text('أدخل رقم هاتفك واختر طريقة استلام رمز التحقق',style:TextStyle(color:Colors.white60,fontSize:15,height:1.5)),const SizedBox(height:38),Row(textDirection:TextDirection.ltr,children:[Container(height:60,width:(MediaQuery.sizeOf(context).width*.34).clamp(120,145).toDouble(),padding:const EdgeInsets.symmetric(horizontal:10),decoration:_field(),child:DropdownButtonHideUnderline(child:DropdownButton<String>(isExpanded:true,value:_countryCode,dropdownColor:const Color(0xFF111827),style:const TextStyle(color:Colors.white,fontSize:14),items:_countries.map((x)=>DropdownMenuItem(value:x.key,child:Text('${x.value}  ${x.key}',overflow:TextOverflow.ellipsis))).toList(),onChanged:(v){if(v!=null)setState(()=>_countryCode=v);}))),const SizedBox(width:10),Expanded(child:Container(height:60,decoration:_field(),child:TextField(controller:_phoneController,keyboardType:TextInputType.number,inputFormatters:[FilteringTextInputFormatter.allow(RegExp(r'[0-9٠-٩۰-۹]'))],onChanged:(v){final n=_digits(v);if(n!=v)_phoneController.value=TextEditingValue(text:n,selection:TextSelection.collapsed(offset:n.length));},textDirection:TextDirection.ltr,style:const TextStyle(color:Colors.white,fontSize:17),decoration:const InputDecoration(hintText:'50 123 4567',hintStyle:TextStyle(color:Colors.white38),prefixIcon:Icon(Icons.phone_iphone_rounded,color:_gold),border:InputBorder.none,contentPadding:EdgeInsets.symmetric(horizontal:14,vertical:18)))))]),const SizedBox(height:12),const Text('اختر SMS أو WhatsApp لاستلام الرمز',style:TextStyle(color:Colors.white38,fontSize:13)),const SizedBox(height:30),_GradientButton(text:'إرسال عبر SMS',loading:state is AuthLoading,onPressed:_sendSms),const SizedBox(height:14),_WhatsAppButton(loading:state is AuthLoading,onPressed:_sendWhatsApp),const SizedBox(height:24),const Text('بالمتابعة أنت توافق على شروط الاستخدام وسياسة الخصوصية',textAlign:TextAlign.center,style:TextStyle(color:Colors.white38,fontSize:12,height:1.5))]));

  Widget _otpView(AuthState state)=>SingleChildScrollView(key:const ValueKey('otp'),padding:const EdgeInsets.fromLTRB(20,20,20,30),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const SizedBox(height:28),const Text('رمز التحقق',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:10),const Text('أرسلنا رمزاً إلى',style:TextStyle(color:Colors.white60,fontSize:15)),const SizedBox(height:6),Text(_fullPhone,textDirection:TextDirection.ltr,style:const TextStyle(color:_gold,fontSize:16,fontWeight:FontWeight.bold)),const SizedBox(height:42),Directionality(textDirection:TextDirection.ltr,child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:List.generate(6,(i)=>SizedBox(width:48,height:58,child:TextField(controller:_otpControllers[i],focusNode:_otpFocus[i],keyboardType:TextInputType.number,textAlign:TextAlign.center,maxLength:6,inputFormatters:[FilteringTextInputFormatter.allow(RegExp(r'[0-9٠-٩۰-۹]'))],style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.bold),decoration:InputDecoration(counterText:'',filled:true,fillColor:const Color(0x99111A2B),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:const BorderSide(color:Color(0xFF34435A))),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:const BorderSide(color:_pink,width:2))),onChanged:(v)=>_handleOtp(i,v)))))),const SizedBox(height:22),Center(child:TextButton(onPressed:state is AuthLoading||_seconds>0?null:_sendSms,child:Text(_seconds>0?'إعادة الإرسال بعد ${(_seconds~/60).toString().padLeft(2,'0')}:${(_seconds%60).toString().padLeft(2,'0')}':'إعادة إرسال عبر SMS',style:TextStyle(color:_seconds>0?Colors.white30:_gold)))),const SizedBox(height:16),_GradientButton(text:'تحقق',loading:state is AuthLoading,onPressed:_verify)]));
}

class _GradientButton extends StatelessWidget{final String text;final bool loading;final VoidCallback onPressed;const _GradientButton({required this.text,required this.loading,required this.onPressed});@override Widget build(BuildContext context)=>SizedBox(height:58,child:DecoratedBox(decoration:BoxDecoration(borderRadius:BorderRadius.circular(17),gradient:const LinearGradient(colors:[Color(0xFF8A00FF),Color(0xFFE000FF)]),boxShadow:const[BoxShadow(color:Color(0x558A00FF),blurRadius:18)]),child:TextButton(onPressed:loading?null:onPressed,child:loading?const SizedBox(width:24,height:24,child:CircularProgressIndicator(strokeWidth:2.5,color:Colors.white)):Text(text,style:const TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)))));}
class _WhatsAppButton extends StatelessWidget{final bool loading;final VoidCallback onPressed;const _WhatsAppButton({required this.loading,required this.onPressed});@override Widget build(BuildContext context)=>SizedBox(height:58,child:OutlinedButton.icon(onPressed:loading?null:onPressed,icon:const Icon(Icons.chat_rounded,size:25),label:const Text('إرسال عبر WhatsApp',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),style:OutlinedButton.styleFrom(foregroundColor:_LoginScreenState._green,side:const BorderSide(color:_LoginScreenState._green,width:1.6),backgroundColor:const Color(0x1425D366),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(17)))));}
